logging:
  level:
    liquibase: INFO

spring:
  jpa:
    show-sql: true
    # open-in-view: false

  datasource:
    url: jdbc:postgresql://localhost:5432/orderdb
    username: postgresuser
    password: postgrespw

redis:
  expirationTimeMinute: 1
